### PR TITLE
Add example OpenAI wrapper analytic for ranking suspicious processes

### PR DESCRIPTION
**Pull request by mayaCostantini**
The goal of this analytic is to offer a base for prompting an OpenAI model (here ChatGPT) to rank suspicious processes given in the input dataframe.

### CODE REVIEW

**Comment by mayaCostantini** [comment]
cc @subbyte @kpeeples

**Review by subbyte — COMMENTED** [review]
Nice!

Would you want to provide a screenshot for people to quickly make sense of this analytics?

And is it helpful to give a little more detailed instructions in the prompt about which field/attribute for GPTs to focus on, e.g., `name` and `command_line` to help it finish its job?

**Comment by mayaCostantini** [comment]
Thanks for the review @subbyte ! Here is a screenshot of the analytic applied to a list of processes as extracted from another example huntbook, with the original prompt from this PR:
Screenshot from 2024-04-26 10-15-00

**Comment by mayaCostantini** [comment]
And as suggested, here is the result when asking the model to focus on the `name` and `command_line` attributes instead:
Screenshot from 2024-04-26 10-18-01

The answer looks indeed more useful with the new prompt, so I will change it.

**Comment by subbyte** [comment]
Cool! Could we have the screenshot as a file like `analytics/openai-suspicious-processes/screenshot.png`?

And it looks like GPT just grab all processes from the JSON and try to rank them, not understand the variable (in this test) only has one process and all other processes are related ones such as parent process---this requires the understanding of the attributes in the exported JSON, which may requires few shots examples to help the LLM. Anyway, a good starting point, and it is great to see that GPT gives some ideas how these processes can be used in an attack.

**Comment by mayaCostantini** [comment]
Thanks! I will follow-up soon with the improvement you proposed

**Review by subbyte — APPROVED** [review]

**Pull request merged**
